// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: texasHoldemService.proto

package com.baischer.service.grpc;

public interface CompareHandsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CompareHandsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hand1 = 1;</code>
   */
  java.lang.String getHand1();
  /**
   * <code>string hand1 = 1;</code>
   */
  com.google.protobuf.ByteString
      getHand1Bytes();

  /**
   * <code>string hand2 = 2;</code>
   */
  java.lang.String getHand2();
  /**
   * <code>string hand2 = 2;</code>
   */
  com.google.protobuf.ByteString
      getHand2Bytes();
}
