// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: texasHoldemService.proto

package com.baischer.service.grpc;

public interface GetHandValueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetHandValueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * e.g. "CT CJ CQ CK CA"
   * </pre>
   *
   * <code>string hand = 1;</code>
   */
  java.lang.String getHand();
  /**
   * <pre>
   * e.g. "CT CJ CQ CK CA"
   * </pre>
   *
   * <code>string hand = 1;</code>
   */
  com.google.protobuf.ByteString
      getHandBytes();
}
