// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: texasHoldemService.proto

package com.baischer.service.grpc;

public interface GetHandValueResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetHandValueResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * e.g. "THREEOFAKIND"
   * </pre>
   *
   * <code>string hand_value = 1;</code>
   */
  java.lang.String getHandValue();
  /**
   * <pre>
   * e.g. "THREEOFAKIND"
   * </pre>
   *
   * <code>string hand_value = 1;</code>
   */
  com.google.protobuf.ByteString
      getHandValueBytes();
}
