// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: texasHoldemService.proto

package com.baischer.service.grpc;

/**
 * Protobuf type {@code GetHandValueRequest}
 */
public  final class GetHandValueRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetHandValueRequest)
    GetHandValueRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetHandValueRequest.newBuilder() to construct.
  private GetHandValueRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetHandValueRequest() {
    hand_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetHandValueRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            hand_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.baischer.service.grpc.TexasHoldemServiceOuterClass.internal_static_GetHandValueRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.baischer.service.grpc.TexasHoldemServiceOuterClass.internal_static_GetHandValueRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.baischer.service.grpc.GetHandValueRequest.class, com.baischer.service.grpc.GetHandValueRequest.Builder.class);
  }

  public static final int HAND_FIELD_NUMBER = 1;
  private volatile java.lang.Object hand_;
  /**
   * <pre>
   * e.g. "CT CJ CQ CK CA"
   * </pre>
   *
   * <code>string hand = 1;</code>
   */
  public java.lang.String getHand() {
    java.lang.Object ref = hand_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hand_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g. "CT CJ CQ CK CA"
   * </pre>
   *
   * <code>string hand = 1;</code>
   */
  public com.google.protobuf.ByteString
      getHandBytes() {
    java.lang.Object ref = hand_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hand_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHandBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hand_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHandBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hand_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.baischer.service.grpc.GetHandValueRequest)) {
      return super.equals(obj);
    }
    com.baischer.service.grpc.GetHandValueRequest other = (com.baischer.service.grpc.GetHandValueRequest) obj;

    boolean result = true;
    result = result && getHand()
        .equals(other.getHand());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HAND_FIELD_NUMBER;
    hash = (53 * hash) + getHand().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.baischer.service.grpc.GetHandValueRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.baischer.service.grpc.GetHandValueRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.baischer.service.grpc.GetHandValueRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.baischer.service.grpc.GetHandValueRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.baischer.service.grpc.GetHandValueRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.baischer.service.grpc.GetHandValueRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.baischer.service.grpc.GetHandValueRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.baischer.service.grpc.GetHandValueRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.baischer.service.grpc.GetHandValueRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.baischer.service.grpc.GetHandValueRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.baischer.service.grpc.GetHandValueRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.baischer.service.grpc.GetHandValueRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.baischer.service.grpc.GetHandValueRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetHandValueRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetHandValueRequest)
      com.baischer.service.grpc.GetHandValueRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baischer.service.grpc.TexasHoldemServiceOuterClass.internal_static_GetHandValueRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baischer.service.grpc.TexasHoldemServiceOuterClass.internal_static_GetHandValueRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baischer.service.grpc.GetHandValueRequest.class, com.baischer.service.grpc.GetHandValueRequest.Builder.class);
    }

    // Construct using com.baischer.service.grpc.GetHandValueRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hand_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.baischer.service.grpc.TexasHoldemServiceOuterClass.internal_static_GetHandValueRequest_descriptor;
    }

    @java.lang.Override
    public com.baischer.service.grpc.GetHandValueRequest getDefaultInstanceForType() {
      return com.baischer.service.grpc.GetHandValueRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.baischer.service.grpc.GetHandValueRequest build() {
      com.baischer.service.grpc.GetHandValueRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.baischer.service.grpc.GetHandValueRequest buildPartial() {
      com.baischer.service.grpc.GetHandValueRequest result = new com.baischer.service.grpc.GetHandValueRequest(this);
      result.hand_ = hand_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.baischer.service.grpc.GetHandValueRequest) {
        return mergeFrom((com.baischer.service.grpc.GetHandValueRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.baischer.service.grpc.GetHandValueRequest other) {
      if (other == com.baischer.service.grpc.GetHandValueRequest.getDefaultInstance()) return this;
      if (!other.getHand().isEmpty()) {
        hand_ = other.hand_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.baischer.service.grpc.GetHandValueRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.baischer.service.grpc.GetHandValueRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object hand_ = "";
    /**
     * <pre>
     * e.g. "CT CJ CQ CK CA"
     * </pre>
     *
     * <code>string hand = 1;</code>
     */
    public java.lang.String getHand() {
      java.lang.Object ref = hand_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hand_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g. "CT CJ CQ CK CA"
     * </pre>
     *
     * <code>string hand = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHandBytes() {
      java.lang.Object ref = hand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g. "CT CJ CQ CK CA"
     * </pre>
     *
     * <code>string hand = 1;</code>
     */
    public Builder setHand(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hand_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. "CT CJ CQ CK CA"
     * </pre>
     *
     * <code>string hand = 1;</code>
     */
    public Builder clearHand() {
      
      hand_ = getDefaultInstance().getHand();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. "CT CJ CQ CK CA"
     * </pre>
     *
     * <code>string hand = 1;</code>
     */
    public Builder setHandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hand_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetHandValueRequest)
  }

  // @@protoc_insertion_point(class_scope:GetHandValueRequest)
  private static final com.baischer.service.grpc.GetHandValueRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.baischer.service.grpc.GetHandValueRequest();
  }

  public static com.baischer.service.grpc.GetHandValueRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetHandValueRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetHandValueRequest>() {
    @java.lang.Override
    public GetHandValueRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetHandValueRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetHandValueRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetHandValueRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.baischer.service.grpc.GetHandValueRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

