// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: texasHoldemService.proto

package com.baischer.service.grpc;

/**
 * Protobuf type {@code GetProbabilityToWinResponse}
 */
public  final class GetProbabilityToWinResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetProbabilityToWinResponse)
    GetProbabilityToWinResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetProbabilityToWinResponse.newBuilder() to construct.
  private GetProbabilityToWinResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetProbabilityToWinResponse() {
    probability_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetProbabilityToWinResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            probability_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.baischer.service.grpc.TexasHoldemServiceOuterClass.internal_static_GetProbabilityToWinResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.baischer.service.grpc.TexasHoldemServiceOuterClass.internal_static_GetProbabilityToWinResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.baischer.service.grpc.GetProbabilityToWinResponse.class, com.baischer.service.grpc.GetProbabilityToWinResponse.Builder.class);
  }

  public static final int PROBABILITY_FIELD_NUMBER = 1;
  private double probability_;
  /**
   * <pre>
   * e.g. 0.16
   * </pre>
   *
   * <code>double probability = 1;</code>
   */
  public double getProbability() {
    return probability_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (probability_ != 0D) {
      output.writeDouble(1, probability_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (probability_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, probability_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.baischer.service.grpc.GetProbabilityToWinResponse)) {
      return super.equals(obj);
    }
    com.baischer.service.grpc.GetProbabilityToWinResponse other = (com.baischer.service.grpc.GetProbabilityToWinResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getProbability())
        == java.lang.Double.doubleToLongBits(
            other.getProbability()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROBABILITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getProbability()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.baischer.service.grpc.GetProbabilityToWinResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.baischer.service.grpc.GetProbabilityToWinResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.baischer.service.grpc.GetProbabilityToWinResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.baischer.service.grpc.GetProbabilityToWinResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.baischer.service.grpc.GetProbabilityToWinResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.baischer.service.grpc.GetProbabilityToWinResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.baischer.service.grpc.GetProbabilityToWinResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.baischer.service.grpc.GetProbabilityToWinResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.baischer.service.grpc.GetProbabilityToWinResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.baischer.service.grpc.GetProbabilityToWinResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.baischer.service.grpc.GetProbabilityToWinResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.baischer.service.grpc.GetProbabilityToWinResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.baischer.service.grpc.GetProbabilityToWinResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetProbabilityToWinResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetProbabilityToWinResponse)
      com.baischer.service.grpc.GetProbabilityToWinResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.baischer.service.grpc.TexasHoldemServiceOuterClass.internal_static_GetProbabilityToWinResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.baischer.service.grpc.TexasHoldemServiceOuterClass.internal_static_GetProbabilityToWinResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.baischer.service.grpc.GetProbabilityToWinResponse.class, com.baischer.service.grpc.GetProbabilityToWinResponse.Builder.class);
    }

    // Construct using com.baischer.service.grpc.GetProbabilityToWinResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      probability_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.baischer.service.grpc.TexasHoldemServiceOuterClass.internal_static_GetProbabilityToWinResponse_descriptor;
    }

    @java.lang.Override
    public com.baischer.service.grpc.GetProbabilityToWinResponse getDefaultInstanceForType() {
      return com.baischer.service.grpc.GetProbabilityToWinResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.baischer.service.grpc.GetProbabilityToWinResponse build() {
      com.baischer.service.grpc.GetProbabilityToWinResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.baischer.service.grpc.GetProbabilityToWinResponse buildPartial() {
      com.baischer.service.grpc.GetProbabilityToWinResponse result = new com.baischer.service.grpc.GetProbabilityToWinResponse(this);
      result.probability_ = probability_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.baischer.service.grpc.GetProbabilityToWinResponse) {
        return mergeFrom((com.baischer.service.grpc.GetProbabilityToWinResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.baischer.service.grpc.GetProbabilityToWinResponse other) {
      if (other == com.baischer.service.grpc.GetProbabilityToWinResponse.getDefaultInstance()) return this;
      if (other.getProbability() != 0D) {
        setProbability(other.getProbability());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.baischer.service.grpc.GetProbabilityToWinResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.baischer.service.grpc.GetProbabilityToWinResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double probability_ ;
    /**
     * <pre>
     * e.g. 0.16
     * </pre>
     *
     * <code>double probability = 1;</code>
     */
    public double getProbability() {
      return probability_;
    }
    /**
     * <pre>
     * e.g. 0.16
     * </pre>
     *
     * <code>double probability = 1;</code>
     */
    public Builder setProbability(double value) {
      
      probability_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g. 0.16
     * </pre>
     *
     * <code>double probability = 1;</code>
     */
    public Builder clearProbability() {
      
      probability_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetProbabilityToWinResponse)
  }

  // @@protoc_insertion_point(class_scope:GetProbabilityToWinResponse)
  private static final com.baischer.service.grpc.GetProbabilityToWinResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.baischer.service.grpc.GetProbabilityToWinResponse();
  }

  public static com.baischer.service.grpc.GetProbabilityToWinResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetProbabilityToWinResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetProbabilityToWinResponse>() {
    @java.lang.Override
    public GetProbabilityToWinResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetProbabilityToWinResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetProbabilityToWinResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetProbabilityToWinResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.baischer.service.grpc.GetProbabilityToWinResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

