// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: texasHoldemService.proto

package com.baischer.service.grpc;

public interface GetProbabilityToWinResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetProbabilityToWinResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * e.g. 0.16
   * </pre>
   *
   * <code>double probability = 1;</code>
   */
  double getProbability();
}
