// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: texasHoldemService.proto

package com.baischer.service.grpc;

public interface GetProbabilityToWinRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetProbabilityToWinRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * e.g. "DT H8 S5"
   * </pre>
   *
   * <code>string talon_cards = 1;</code>
   */
  java.lang.String getTalonCards();
  /**
   * <pre>
   * e.g. "DT H8 S5"
   * </pre>
   *
   * <code>string talon_cards = 1;</code>
   */
  com.google.protobuf.ByteString
      getTalonCardsBytes();

  /**
   * <pre>
   * e.g. "H4 S2"
   * </pre>
   *
   * <code>string player_pocket_cards = 2;</code>
   */
  java.lang.String getPlayerPocketCards();
  /**
   * <pre>
   * e.g. "H4 S2"
   * </pre>
   *
   * <code>string player_pocket_cards = 2;</code>
   */
  com.google.protobuf.ByteString
      getPlayerPocketCardsBytes();

  /**
   * <pre>
   * e.g. 2
   * </pre>
   *
   * <code>int32 number_of_opponents = 3;</code>
   */
  int getNumberOfOpponents();

  /**
   * <pre>
   * e.g. 888
   * </pre>
   *
   * <code>int32 number_of_simulations = 4;</code>
   */
  int getNumberOfSimulations();
}
